export const FUNIBER_URL_LINKS = {
	AR: "https://www.funiber.org.ar/",
	ES: "https://www.funiber.es/",
	IT: "https://www.funiber.it/",
	PT: "https://www.funiber.pt/",
	BO: "https://www.funiber.org.bo/",
	BR: "https://www.funiber.org.br/",
	CR: "https://www.funiber.or.cr/",
	SV: "https://www.funiber.sv/",
	GT: "https://www.funiber.org.gt/",
	HN: "https://www.funiber.org.hn/",
	NI: "https://www.funiber.org.ni/",
	PA: "https://www.funiber.org.pa/",
	CL: "https://www.funiber.cl/",
	CO: "https://www.funiber.org.co/",
	EC: "https://www.funiber.org.ec/",
	MX: "https://www.funiber.org.mx/",
	PY: "https://www.funiber.org.py/",
	PE: "https://www.funiber.org.pe/",
	PR: "https://www.funiber.org.pr/",
	DO: "https://www.funiber.org.do/",
	UY: "https://www.funiber.org.uy/",
	VE: "https://www.funiber.org.ve/",
	US: "https://www.funiber.us/",
	CN: "https://www.funiber.cn/",
}
